config/routes.rb
Rails.application.routes.draw do

  root 'public/homes#top'
  get 'about' => 'public/homes#about'
  get 'top' => 'admin/homes#top'

  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions',
    :registrations => 'admins/registrations',
    :passwords => 'admins/passwords'
  }

  devise_for :customers, :controllers => {
    :sessions => 'customers/sessions',
    :passwords => 'customers/passwords',
    :registrations => 'customers/registrations'
  }
  get '/customers/my_page' => 'public/customers#show'
  get '/customers/edit/:id' => 'public/customers#edit', as: 'customers_edit'
  patch 'public/customers' => 'public/customers#update'
  get '/customers/check' => 'public/customers#check'
  patch '/customers/withdraw' => 'public/customers#withdraw'

  resources :cart_items, only: [:index, :update, :destroy, :create], module: "public" do
    collection do
      delete '/destroy_all' => 'cart_items#destroy_all'
    end
  end

  resources :items, only: [:index, :show], module: "public"

  resources :orders, only: [:index, :show, :new, :create], module: "public" do
    collection do
      post '/orders/confirm' => 'orders#confirm'
      get '/complete' => 'orders#complete'
    end
  end


  resources :addresses, only: [:index, :edit, :create, :update, :destroy], module: "public"

    namespace :admin do
      resources :customers, only: [:index, :show, :edit, :update]
      resources :items, only: [:index, :new, :create, :show, :edit, :update]
      resources :genres, only: [:index, :create, :edit, :update]
      resources :orders, only: [:index, :show, :update]
      resources :order_details, only: [:update]
    end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  def active_for_authentication?
    super && (is_active == true)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
 # before_action :if_not_admin

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
       flash[:success] = "You have updated book successfully."
       redirect_to admin_customer_path(@customer.id)
    else
      render :edit
    end
  end

  private
  #def if_not_admin
   # redirect_to root_path unless current_user.admin?
  #end
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  protected
  def after_sign_up_path_for(resource)
    customers_my_page_path
  end

end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  protected
  
  def after_sign_in_path_for(resource)
    customers_my_page_path
  end

  def reject_user
    @customer = Customer.find(params[:id])
    if @customer
      if @user.valid_password?(params[:customer][:password]) &&  (@customer.active_for_authentication? == true)
        redirect_to new_customer_registration_path
      end
    end
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-3">
      <h4 class="daimei"><%= @customer.last_name %>　<%= @customer.first_name %>さんの会員情報編集</h4>
    </div>
  </div>
  <div class="bigbox1">
    <table class="table tablebox">
      <tr>
        <th>会員ID</th>
        <td><%= @customer.id %></td>
      </tr>
      <%= form_with model:@customer, url: admin_customer_path(@customer.id), method: :PATCH, local:true do |f| %>
        <tr>
          <th>氏名</th>
          <td><%= f.text_field :last_name %>　　<%= f.text_field :first_name %></td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= f.text_field :last_name_kana %>　　<%= f.text_field :first_name_kana %></td>
        </tr>
      <tr>
        <th>郵便番号</th>
        <td><%= f.text_field :postal_code %></td>
      </tr>
      <tr>
        <th>住所</th>
        <td><%= f.text_area :address, class:"form-control  address", rows:"1" %></td>
      </tr>
      <tr>
        <th>電話番号</th>
        <td><%= f.text_field :telephone_number %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= f.text_field :email %></td>
      </tr>
      <tr>
        <th>会員ステータス</th>
        <td>
        <%= f.radio_button :is_active, true %>
        <%= f.label :is_active, "有効", {value: true, style: "display: inline-block;"} %>
        <%= f.radio_button :is_active, false %>
        <%= f.label :is_active, "退会", {value: false, style: "display: inline-block;"} %>
        </td>
      </tr>
    </table>
    <div class="action">
      <%= f.submit '変更を保存' %>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-3">
      <h4 class="daimei">会員一覧</h4>
    </div>
  </div>
  <table class='table table-hover table-inverse'>
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td><%= link_to admin_customer_path(customer.id) do %><%= customer.last_name %><%= customer.first_name %><% end %></td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.is_active %>
              有効
            <% else %>
              退会
            <% end %>
          </td>
        </tr>
      <% end %>
      <%= paginate @customers %>
    </tbody>
  </table>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-3">
      <h4 class="daimei"><%= @customer.last_name %> <%= @customer.first_name %>さんの会員詳細</h4>
    </div>
  </div>
  <div class="bigbox1">
    <table class='table tablebox'>
      <tr>
        <th>会員ID</th>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <th>氏名</th>
        <td><%= @customer.last_name %>　<%= @customer.first_name %></td>
      </tr>
      <tr>
        <th>フリガナ</th>
        <td><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
      </tr>
      <tr>
        <th>郵便番号</th>
        <td><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <th>住所</th>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <th>電話番号</th>
        <td><%= @customer.telephone_number %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <th>会員ステータス</th>
        <td>
          <% if @customer.is_active %>
            有効
          <% else %>
            退会
          <% end %>
        </td>
      </tr>
    </table>
    <%= link_to "編集する", edit_admin_customer_path(@customer.id), class:"btn btn-sm btn-success", data: {"turbolinks" => false} %>
    <%= link_to "注文履歴一覧を見る", admin_orders_path, class:"btn btn-sm btn-info", data: {"turbolinks" => false} %>
    </div>
</div>