config/routes.rb
Rails.application.routes.draw do

  root 'public/homes#top'
  get 'about' => 'public/homes#about'
  get 'top' => 'admin/homes#top'

  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions',
    :registrations => 'admins/registrations',
    :passwords => 'admins/passwords'
  }

  devise_for :customers, :controllers => {
    :sessions => 'customers/sessions',
    :passwords => 'customers/passwords',
    :registrations => 'customers/registrations'
  }
  get '/customers/my_page' => 'public/customers#show'
  get '/customers/edit/:id' => 'public/customers#edit', as: 'customers_edit'
  patch 'public/customers' => 'public/customers#update'
  get '/customers/check' => 'public/customers#check'
  patch '/customers/withdraw' => 'public/customers#withdraw'

  resources :cart_items, only: [:index, :update, :destroy, :create], module: "public" do
    collection do
      delete '/destroy_all' => 'cart_items#destroy_all'
    end
  end

  resources :items, only: [:index, :show], module: "public"

  resources :orders, only: [:index, :show, :new, :create], module: "public" do
    collection do
      post '/orders/confirm' => 'orders#confirm'
      get '/complete' => 'orders#complete'
    end
  end


  resources :addresses, only: [:index, :edit, :create, :update, :destroy], module: "public"

    namespace :admin do
      resources :customers, only: [:index, :show, :edit, :update]
      resources :items, only: [:index, :new, :create, :show, :edit, :update]
      resources :genres, only: [:index, :create, :edit, :update]
      resources :orders, only: [:index, :show, :update]
      resources :order_details, only: [:update]
    end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer
  
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  def active_for_authentication?
    super && (is_active == true)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum pay_status: { credit_card: 0, transfer: 1 }
  enum order_status: { wait_pay: 0, check_pay: 1, in_production: 2, preparing_ship: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_statuses: { not_maked: 0, wait_maked: 1, now_maked: 2, fin_maked: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
       flash[:success] = "You have updated book successfully."
       redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  #before_action :if_not_admin

  def top
    @orders = Order.page(params[:page]).reverse_order
  end

  #private
  #def if_not_admin
    #redirect_to root_path unless current_user.admin?
  #end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  #before_action :if_not_admin

  def index
    @items = Item.page(params[:page]).order(:id)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = "You have created book successfully."
      redirect_to admin_item_path(@item.id)
    else
      @items = Item.page(params[:page]).order(:id)
      render :index
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
       flash[:success] = "You have updated book successfully."
       redirect_to admin_items_path
    else
      render :edit
    end
  end

  private
  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end
  def item_params
    params.require(:item).permit(:name, :image, :introduction, :genre_id, :price, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  #before_action :if_not_admin

  def index
    @orders = Order.page(params[:page])
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
  end

  def update
   @order = Order.find(params[:id])
   @order_details = @order.order_details
  end

  private
  def order_params
    params.require(:order).permit(:order_status)
  end

  def if_not_admin
    redirect_to root_path unless current_admin.id?
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController

  def new
  end

  def create
  end

  def destroy
  end

  protected
    def after_sign_in_path_for(resource)
      root_to
    end
    def after_sign_out_path_for(resource)
      new_admin_session_path
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-3">
      <h5 class="daimei">ジャンル編集</h5>
    </div>
  </div>

  <div class="box1">
    <%= form_with model: @genre, url: admin_genre_path, method: :patch, local: true do |f| %>
      <table>
        <tr>
          <th>ジャンル名</th>
          <td><%= f.text_field :name %></td>
          <td><%= f.submit '変更を保存', class: "btn btn-success" %></td>
      </tr>
      </table>
    <% end %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-3">
      <h5 class="daimei">ジャンル一覧・追加</h5>
    </div>
  </div>
  <div class="bigbox1">
    <div class="box2">
    <%= form_with model: @genre, url:'/admin/genres', local:true do |f| %>
      <table>
        <tr>
          <th>ジャンル名</th>
          <td><%= f.text_field :name, placeholder:'ジャンル名' %></td>
          <td><%= f.submit '新規登録', class: "btn-success" %></td>
        </tr>
      </table>
    <% end %>
    </div>
  <table class="table tablebox">
    <thead>
      <tr>
        <th>ジャンル</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @genres.each do |genre| %>
        <tr>
          <td><%= genre.name %></td>
          <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-3">
      <h4 class="daimei">商品編集</h4>
    </div>
  </div>
  <div class="bigbox1">
    <%= form_with model: @item, url: admin_item_path(@item.id), method: :PATCH, local:true do |f| %>
      <table class="table tablebox">
        <tr class="mb-2">
          <th class="label">商品画像</th>
          <td>
            <%= f.attachment_field :image %>
          </td>
        </tr>
        <tr class="mb-2">
          <th class="label">商品名</th>
          <td>
            <%= f.text_field :name %>
          </td>
        </tr>
        <tr class="mb-2">
          <th class="label">商品説明</th>
          <td><%= f.text_area :introduction, class:"form-control  introduction", rows:"5" %></td>
        </tr>
        <tr class="mb-2">
          <th class="label">ジャンル</th>
          <td>
            <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %>
          </td>
        </tr>
        <tr class="mb-2">
          <th class="label">税抜き価格</th>
          <td><%= f.text_field :price %><span>円</span></td>
        </tr>
        <tr class="mb-2">
          <th class="label">販売ステータス</th>
          <td>
            <%= f.radio_button :is_active, true %>
            <%= f.label :is_active, "販売中", {value: true, style: "display: inline-block;"} %>
            <%= f.radio_button :is_active, false %>
            <%= f.label :is_active, "販売停止中", {value: false, style: "display: inline-block;"} %>
          </td>
        </tr>
      </table>
      <div class="action">
        <%= f.submit '変更を保存', class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-3">
      <h4 class="daimei">商品一覧</h4><span>
    </div>
  <div class="text-right mt-3"><%= link_to "+", new_admin_item_path, class: "btn btn-info" %></div></span>
  </div>
  <table class='table table-hover'>
    <thead>
      <tr>
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
        <th>ジャンル</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to admin_item_path(item.id) do %><%= item.name %><% end %></td>
          <td><%= item.price %></td>
          <td><%= item.genre.name %></td>
          <td>
            <% if item.is_active %>
              販売中
            <% else %>
              販売停止中
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @items %>
</div>

app/views/admin/items/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-3">
      <h4 class="daimei">商品新規登録</h4>
    </div>
  </div>
  <div class="bigbox1">
    <div class="mainbox1">
    <%= form_with model: @item, url: admin_items_path, method: :POST, local:true do |f| %>
      <table class="tablebox">
        <tr class="mb-2">
          <th class="label">商品画像</th>
          <td>
            <%= f.attachment_field :image %>
          </td>
        </tr>
        <tr class="mb-2">
          <th class="label">商品名</th>
          <td>
            <%= f.text_field :name %>
          </td>
        </tr>
        <tr class="mb-2">
          <th class="label">商品説明</th>
          <td><%= f.text_area :introduction, class:"form-control  introduction", rows:"5" %></td>
        </tr>
        <tr class="mb-2">
          <th class="label">ジャンル</th>
          <td>
            <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "選択して下さい" %>
          </td>
        </tr>
        <tr class="mb-2">
          <th class="label">税抜き価格</th>
          <td><%= f.text_field :price %><span>円</span></td>
        </tr>
        <tr class="mb-2">
          <th class="label">販売ステータス</th>
          <td>
            <%= f.radio_button :is_active, true %>
            <%= f.label :is_active, "販売中", {value: true, style: "display: inline-block;"} %>
            <%= f.radio_button :is_active, false %>
            <%= f.label :is_active, "販売停止中", {value: false, style: "display: inline-block;"} %>
          </td>
        </tr>
      </table>
      <div class="action1">
        <%= f.submit '新規登録', class: "btn btn-success" %>
      </div>

  <% end %>
  </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-3">
      <h4 class="daimei">商品詳細</h4>
    </div>
  </div>
  <div class="bigbox1">
  <div class="mainbox1">
    <%= attachment_image_tag @item, :image, :fill, 200, 200, fallback: "no_image.jpg" %>
  </div>
  <div class="mainbox1">
    <table class='table tablebox'>
      <tr>
        <th>商品名</th>
        <td><%= @item.name %></td>
      </tr>
      <tr>
        <th>商品説明</th>
        <td><%= @item.introduction %></td>
      </tr>
      <tr>
        <th>ジャンル</th>
        <td><%= @item.genre.name %></td>
      </tr>
      <tr>
        <th>税込価格</br>(税抜価格)</th>
        <td><%= (@item.price*1.1).floor %><span>(<%= @item.price %>)円</td>
      </tr>
      <tr>
        <th>販売ステータス</th>
        <td>
          <% if @item.is_active %>
            販売中
          <% else %>
            販売停止中
          <% end %>
        </td>
      </tr>
    </table>
  </div>
  <div class="">
    <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-sm btn-success", data: {"turbolinks" => false} %>
  </div>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-3">
      <h4 class="daimei">注文履歴一覧</h4>
    </div>
  </div>
  <table class='table table-hover'>
    <thead>
      <tr>
        <th>購入日時</th>
        <th>購入者</th>
        <th>注文個数</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= link_to admin_order_path(order.id) do %><%= I18n.l(order.created_at) %><% end %></td>
          <td><%= order.name %></td>
          <td>
            <% amount = 0 %>
            <% order.order_details.each do |detail| %>
              <% detail.amount %>
              <% amount = amount + detail.amount %>
            <% end %>
            <%= amount %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @orders %>
</div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-3">
      <h4 class="daimei">注文履歴詳細</h4>
    </div>
  </div>
  <div class="row">
    <div class="col-10">
    <table class='table'>
      <tr>
        <th>購入者</th>
        <td><%= link_to admin_orders_path do %><%= @order.name %><% end %></td>
      </tr>
      <tr>
        <th>注文日</th>
        <td><%= I18n.l(@order.created_at) %></td>
      </tr>
      <tr>
        <th>配送先</th>
        <td><%= @order.address %></br><%= @order.name %></td>
      </tr>
      <tr>
        <th>支払方法</th>
        <td><%= @order.pay_status_i18n %></td>
      </tr>
    </table>
    </div>
  </div>
  <div class="row">
    <div class="col-7">
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th>商品名</th>
          <th>単価(税込み)</th>
          <th>数量</th>
          <th>小計</th>
        </tr>
      </thead>
      <tbody>
        <% subtotal=0 %>
        <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.item.with_tax_price %></td>
            <td><%= order_detail.amount %></td>
            <td><%= order_detail.item.with_tax_price * order_detail.amount %></td>
            <% sum = order_detail.item.with_tax_price * order_detail.amount %>
            <% subtotal = subtotal + sum %>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
    <div class="col-1"></div>
    <div class="col-4">
      <table class="table table-borderless">
        <tr>
          <th>商品合計</th>
          <td><%= subtotal %></td>
        </tr>
        <tr>
          <th>送料</th>
          <td><%= @order.postage %></td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td><%= @order.price %></td>
        </tr>
      </table>
    </div>
  </div>
</div>