config/routes.rb
Rails.application.routes.draw do

  root 'public/homes#top'
  get 'about' => 'public/homes#about'
  get 'top' => 'admin/homes#top'

  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions',
    :registrations => 'admins/registrations',
    :passwords => 'admins/passwords'
  }

  devise_for :customers, :controllers => {
    :sessions => 'customers/sessions',
    :passwords => 'customers/passwords',
    :registrations => 'customers/registrations'
  }
  get '/customers/my_page' => 'public/customers#show'
  get '/customers/edit/:id' => 'public/customers#edit', as: 'customers_edit'
  patch 'public/customers' => 'public/customers#update'
  get '/customers/check' => 'public/customers#check'
  patch '/customers/withdraw' => 'public/customers#withdraw'

  resources :cart_items, only: [:index, :update, :destroy, :create], module: "public" do
    collection do
      delete '/destroy_all' => 'cart_items#destroy_all'
    end
  end

  resources :items, only: [:index, :show], module: "public"

  resources :orders, only: [:index, :show, :new, :create], module: "public" do
    collection do
      post '/orders/confirm' => 'orders#confirm'
      get '/complete' => 'orders#complete'
    end
  end


  resources :addresses, only: [:index, :edit, :create, :update, :destroy], module: "public"

    namespace :admin do
      resources :customers, only: [:index, :show, :edit, :update]
      resources :items, only: [:index, :new, :create, :show, :edit, :update]
      resources :genres, only: [:index, :create, :edit, :update]
      resources :orders, only: [:index, :show, :update]
      resources :order_details, only: [:update]
    end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer
  
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  def active_for_authentication?
    super && (is_active == true)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  attachment :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum pay_status: { credit_card: 0, transfer: 1 }
  enum order_status: { wait_pay: 0, check_pay: 1, in_production: 2, preparing_ship: 3, shipped: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
  enum making_statuses: { not_maked: 0, wait_maked: 1, now_maked: 2, fin_maked: 3 }
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  #before_action :if_not_admin

  def top
    @orders = Order.page(params[:page]).reverse_order
  end

  #private
  #def if_not_admin
    #redirect_to root_path unless current_user.admin?
  #end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  #before_action :if_not_admin

  def index
    @items = Item.page(params[:page]).order(:id)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:success] = "You have created book successfully."
      redirect_to admin_item_path(@item.id)
    else
      @items = Item.page(params[:page]).order(:id)
      render :index
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
       flash[:success] = "You have updated book successfully."
       redirect_to admin_items_path
    else
      render :edit
    end
  end

  private
  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end
  def item_params
    params.require(:item).permit(:name, :image, :introduction, :genre_id, :price, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if customer_signed_in? %>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <div><%= link_to 'ながのCAKE', root_path, class: "navbar-brand" %></div>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <div class="text-light">ようこそ、<%= @customer.first_name %>さん！</div>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to 'マイページ', customers_my_page_path, class: 'fas fa-home nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to '商品一覧', items_path, class: 'fas fa-users nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to 'カート', cart_items_path, class: 'fas fa-book-open nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: 'nav-link text-light' %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
  <% elsif admin_signed_in? %>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <div><%= link_to 'ながのCAKE', root_path, class: "navbar-brand" %></div>
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to '商品一覧', admin_items_path, class: 'fas fa-home nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to '会員一覧', admin_customers_path, class: 'fas fa-users nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to '注文履歴一覧', admin_orders_path, class: 'fas fa-book-open nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ジャンル一覧', admin_genres_path, class: 'fas fa-book-open nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link text-light' %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
  <% else %>
    <header>
      <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <div><%= link_to 'ながのCAKE', root_path, class: "navbar-brand" %></div>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to 'About', about_path, class: 'fas fa-home nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to '商品一覧', items_path, class: 'fas fa-users nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to '新規登録', new_customer_registration_path, class: 'fas fa-book-open nav-link text-light' %>
              </li>
              <li class="nav-item">
                <%= link_to 'ログイン', new_customer_session_path, class: 'nav-link text-light' %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    </header>
  <% end %>
  <main class="mb-auto">
    <%= yield %>
  </main>
  <footer>
    <div class='container mt-5'>
      <div class='row'>
        </div>
    </div>
  </footer>
  </body>
</html>